// <auto-generated />
namespace MVCMailSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mailboxID_to_GUID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mailboxID_to_GUID));
        
        string IMigrationMetadata.Id
        {
            get { return "201503132346324_mailboxID_to_GUID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
