// <auto-generated />
namespace MVCMailSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class drop_mailboxes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(drop_mailboxes));
        
        string IMigrationMetadata.Id
        {
            get { return "201503132319201_drop_mailboxes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
